#!/bin/bash

kick_livy_server(){

    echo "starting Livy Server!"
    /opt/livy-0.5.0-incubating-bin/bin/livy-server start 

    # whatever blocking call 
    tail -f /dev/null
}

start_server(){

    kick_livy_server
    if [[ $? != 0 ]]; then
        echo "start failed. exiting now." >&2
        exit 1
    fi
}

exit_alert() {
    if [[ $1 -ne 0 ]]; then 
        shift
        echo "$1 failed, exiting" 
        exit 1
    else    
        echo "$1 Success."
    fi
}


##-- Main Execution Starts Here --##
## Set Home directories.

if [[ "$1" == "" ]]; then
    echo "Calling the start... "

    start_server 
    exit_alert "start" $?  
else
    exec "$@"
fi